#ifndef ACTION_DECODER_H
#define ACTION_DECODER_H

#include "Action.h"
#include "Game.h"

namespace ActionRanges {
    const int DRIVE_START = 0;
    const int DIRECT_FLIGHT_START = DRIVE_START + NUMBER_OF_CITIES;
    const int CHARTER_FLIGHT_START = DIRECT_FLIGHT_START + NUMBER_OF_CITIES;
    const int SHUTTLE_FLIGHT_START = CHARTER_FLIGHT_START + NUMBER_OF_CITIES;

    const int BUILD_STATION = SHUTTLE_FLIGHT_START + NUMBER_OF_CITIES;     
    const int TREAT_DISEASE_START = BUILD_STATION + NUMBER_OF_CITIES;
    const int SHARE_START = TREAT_DISEASE_START + NUMBER_OF_COLORS;
    const int CURE_DISEASE_START = SHARE_START + NUMBER_OF_MAX_PLAYERS * NUMBER_OF_CITIES;

    const int CONTINGENCY_USE_START = CURE_DISEASE_START + NUMBER_OF_COLORS;
    const int CONTINGENCY_TAKE_START = CONTINGENCY_USE_START + 1;

    const int DISPATCHER_MOVE_START = CONTINGENCY_TAKE_START + NUMBER_OF_EVENT_CARDS;

    const int OPS_EXPERT_BUILD_START = DISPATCHER_MOVE_START + NUMBER_OF_MAX_PLAYERS * NUMBER_OF_CITIES;
    const int OPS_EXPERT_MOVE_START = OPS_EXPERT_BUILD_START + NUMBER_OF_CITIES;

    const int GOVERMENT_GRANT_START = OPS_EXPERT_MOVE_START + NUMBER_OF_CITIES;
    const int FORECAST_START = GOVERMENT_GRANT_START + NUMBER_OF_CITIES;
    const int RESILIENT_POP_START = FORECAST_START + 1;
    const int ONE_QUIET_NIGHT_START = RESILIENT_POP_START + NUMBER_OF_CITIES;
    const int AIRLIFT_START = ONE_QUIET_NIGHT_START + 1;

    const int DISCARD_CARD_START = AIRLIFT_START + NUMBER_OF_MAX_PLAYERS * NUMBER_OF_CITIES;
    const int REMOVE_STATION_START = DISCARD_CARD_START + NUMBER_OF_CITIES + NUMBER_OF_EVENT_CARDS;
    const int END_TURN_START = REMOVE_STATION_START + NUMBER_OF_CITIES;
    const int COUNT = END_TURN_START + 1;
}

class ActionDecoder {
public:
    // Neural Net (Int) -> Game Engine (Action)
    static Action GetActionFromIndex(int index, const GameState& state);

    // Game Engine (Action) -> Neural Net (Int)
    // Returns -1 if the action cannot be mapped (shouldn't happen)
    static int GetIndexFromAction(const Action& action);
};

#endif
